# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # nice_nano_v2 -> nice_nano//zmk (Zephyr 4.1 / ZMK board variant)
  - board: nice_nano//zmk
    shield: vanana_rev2

  # nice_nano (v1) -> nice_nano@1//zmk
  - board: nice_nano@1//zmk
    shield: waaffle_rev3

  - board: nice_nano//zmk
    shield: waaffle_rev3
